import CoreLocation
import MapKit

/// **Is this point in New England?** Answered on the phone, from an outline
/// shipped inside the app, and the coordinate goes nowhere.
///
/// The only containment test in the app. Rectangles cannot do this job: the
/// opening camera's box leaves out Lubec and Fort Kent, and any box that takes
/// in all of Maine also takes in Montauk, Sherbrooke and Edmundston. Rectangles
/// are for ranking search, never for deciding what is in.
///
/// The outline is the six states from the Census Bureau's public-domain
/// cartographic boundaries, unioned, pushed 500 m out to sea and over each
/// border, and simplified. `NewEnglandBoundary.swift` is generated by
/// `tools/build_new_england_boundary.py`, and its header records exactly what
/// was done and what was measured. So a point a few hundred metres over the
/// line into New York or Quebec counts as inside, which is harmless: the server
/// takes any point within 5 km of one of its roads.
enum NewEngland {

    /// Whether a coordinate is in New England, or within a few hundred metres
    /// of its coast or borders.
    ///
    /// A bounding box first, then a crossing test over only the rings whose
    /// own boxes hold the point. Any point near New England walks the
    /// mainland's ring, so that is the cost: measured at 4.4 µs a call
    /// optimised and 0.7 ms in a Debug build, on a Mac. Cheap enough for
    /// every fix and every keystroke.
    static func contains(_ coordinate: CLLocationCoordinate2D) -> Bool {
        let lat = coordinate.latitude, lon = coordinate.longitude
        // Also rejects NaN, since every comparison with it is false.
        guard lat >= NewEnglandBoundary.south, lat <= NewEnglandBoundary.north,
              lon >= NewEnglandBoundary.west, lon <= NewEnglandBoundary.east
        else { return false }
        return rings.contains { $0.contains(lat: lat, lon: lon) }
    }

    /// The six states, by postal code.
    static let stateCodes: Set<String> = ["CT", "ME", "MA", "NH", "RI", "VT"]

    // MARK: - What the app says

    /// For a search that found places, none of them in New England.
    static func notInNewEngland(_ label: String) -> String {
        "“\(label)” isn’t in New England. Sunday Drive only covers the six New England states."
    }

    /// For My Location, or the Loop row, with the phone outside.
    static let outsideHere = "You’re outside New England, so this can’t start from your location. "
        + "Type a New England town as your start."

    // MARK: - Resolving a search

    /// The first search result that is in New England, or nil.
    ///
    /// **The hard guarantee.** Suggestions are only filtered by what their
    /// labels say, and a typed search only ranked, so this is the one place
    /// that decides what becomes a start or a destination, on every iOS
    /// version. "The first in New England" rather than "the first": a name
    /// shared by several states comes back in whatever order Apple ranks it,
    /// and from Cupertino a typed "Portland" answered with Oregon.
    static func firstInside(_ items: [MKMapItem]) -> MKMapItem? {
        items.first { accepts($0.placemark.coordinate, administrativeArea: $0.placemark.administrativeArea) }
    }

    /// A result is in when it is inside the outline and, if it names a state,
    /// names one of the six.
    ///
    /// The state is checked as well because the outline reaches a few hundred
    /// metres over each border: Stanstead, Quebec, is inside it.
    static func accepts(_ coordinate: CLLocationCoordinate2D, administrativeArea: String?) -> Bool {
        guard contains(coordinate) else { return false }
        guard let area = administrativeArea?.trimmingCharacters(in: .whitespaces),
              !area.isEmpty else { return true }
        return stateCodes.contains(area.uppercased()) || stateNames.contains(area.lowercased())
    }

    private static let stateNames: Set<String> = [
        "connecticut", "maine", "massachusetts", "new hampshire", "rhode island", "vermont",
    ]

    // MARK: - Filtering suggestions

    /// Whether to show an autocomplete suggestion, judged by its label alone.
    ///
    /// A suggestion carries no coordinate, only the two strings Apple shows,
    /// so this reads them. **Built from strings captured on the iOS 26.4
    /// simulator**, not imagined ones, and those disagreed with the obvious
    /// design in two ways:
    ///
    /// - **A city's state is in its title, not its subtitle.** "Portland, OR"
    ///   comes back over the subtitle "United States". Reading only the
    ///   subtitle would have kept every out-of-state city.
    /// - **`regionPriority = .required` does not restrict the completer.**
    ///   With the region pinned to New England, "Times Square" still offered
    ///   Mumbai and "Paris" still offered France. The restriction works for a
    ///   typed search (`MKLocalSearch`) and not here, so on every iOS version
    ///   this filter is the whole of the defence for suggestions.
    ///   `firstInside` stands behind it.
    ///
    /// The rule: find the last state or province code in the subtitle, or
    /// failing that at the end of the title. One of the six keeps the
    /// suggestion; any other US state or Canadian province drops it. With no
    /// code at all, a subtitle that ends in a foreign country's name drops it,
    /// and anything else is kept — a bare street address ("65-66 Beacon St")
    /// is how some Boston results arrive.
    static func allowsSuggestion(title: String, subtitle: String) -> Bool {
        if let code = lastRegionCode(in: subtitle) ?? trailingRegionCode(in: title) {
            return stateCodes.contains(code)
        }
        guard let country = subtitle.split(separator: ",").last?
                .trimmingCharacters(in: .whitespaces).lowercased()
        else { return true }
        return !foreignCountryNames.contains(country)
    }

    /// The last code in a subtitle, scanning its comma-separated parts.
    private static func lastRegionCode(in text: String) -> String? {
        text.split(separator: ",").compactMap { regionCode(in: String($0)) }.last
    }

    /// A code that is the whole last part of a title, as in "Portland, OR".
    /// Only the last part, so a business named after a place keeps its name.
    private static func trailingRegionCode(in title: String) -> String? {
        let parts = title.split(separator: ",")
        guard parts.count > 1, let last = parts.last else { return nil }
        return regionCode(in: String(last))
    }

    /// A state or province code inside one part of an address.
    ///
    /// A code is two capital letters followed by nothing but a postal code,
    /// which covers every shape captured: "MA", "MA  02114", "OR 97218-1009",
    /// "Montréal QC", "Sherbrooke QC J1K 2R1". It is matched as a whole word,
    /// so the letters "ME" inside a word are not Maine, and "NE" in
    /// "7000 NE Airport Way" is a direction, not Nebraska.
    private static func regionCode(in part: String) -> String? {
        let words = part.split(whereSeparator: \.isWhitespace).map(String.init)
        for (index, word) in words.enumerated() where isCode(word) {
            let rest = words[(index + 1)...]
            if rest.isEmpty || isUSPostalCode(rest) || isCanadianPostalCode(rest) {
                return word
            }
        }
        return nil
    }

    private static func isCode(_ word: String) -> Bool {
        word.count == 2 && (stateCodes.contains(word) || otherRegionCodes.contains(word))
    }

    /// "02114" or "97218-1009".
    private static func isUSPostalCode(_ words: ArraySlice<String>) -> Bool {
        guard words.count == 1, let zip = words.first else { return false }
        let digits = zip.split(separator: "-", omittingEmptySubsequences: false)
        return digits.first?.count == 5
            && digits.allSatisfy { !$0.isEmpty && $0.allSatisfy(\.isASCII) && $0.allSatisfy(\.isNumber) }
    }

    /// "J1K 2R1": letter, digit, letter, then digit, letter, digit.
    private static func isCanadianPostalCode(_ words: ArraySlice<String>) -> Bool {
        let joined = words.joined()
        guard joined.count == 6 else { return false }
        return joined.enumerated().allSatisfy { index, character in
            character.isASCII && (index.isMultiple(of: 2) ? character.isLetter : character.isNumber)
        }
    }

    /// Every US state, DC and the territories, and every Canadian province
    /// and territory: the codes that mean "somewhere else".
    private static let otherRegionCodes: Set<String> = [
        "AL", "AK", "AZ", "AR", "CA", "CO", "DE", "FL", "GA", "HI", "ID", "IL", "IN",
        "IA", "KS", "KY", "LA", "MD", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NJ",
        "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "SC", "SD", "TN", "TX", "UT",
        "VA", "WA", "WV", "WI", "WY", "DC", "PR", "VI", "GU", "AS", "MP",
        "AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT",
    ]

    /// Every country's name except the United States', in the phone's
    /// language and in English, plus the four the UK is written as.
    ///
    /// Country names are localised, so nothing here depends on recognising
    /// "United States". That is why this only ever *drops*: a name it does not
    /// know is kept and left to `firstInside`.
    private static let foreignCountryNames: Set<String> = {
        let languages = [Locale.current, Locale(identifier: "en_US")]
        var names: Set<String> = ["england", "scotland", "wales", "northern ireland"]
        for region in Locale.Region.isoRegions {
            let code = region.identifier
            guard code.count == 2, code.allSatisfy(\.isLetter), code != "US" else { continue }
            for language in languages {
                if let name = language.localizedString(forRegionCode: code) {
                    names.insert(name.lowercased())
                }
            }
        }
        for language in languages {
            if let us = language.localizedString(forRegionCode: "US") { names.remove(us.lowercased()) }
        }
        return names
    }()

    // MARK: - Ranking search

    /// Where to rank search results, and whether to insist on that region.
    struct SearchBias {
        let region: MKCoordinateRegion
        /// True when `region` is the New England envelope standing in for a
        /// bias that had left New England.
        let restricted: Bool
    }

    /// The region to rank a search around, kept to New England.
    ///
    /// **A tight bias inside New England is kept**, because completions rank
    /// by distance from the region's centre, and that is what stops "main
    /// street" offering one four towns away (`MKCoordinateRegion.around`).
    /// **A bias that has left New England is replaced by the envelope**: the
    /// map showing Cupertino after its locate button, or the 30 km box around
    /// a fix taken there. So is one wider than New England, the whole-region
    /// camera at launch.
    ///
    /// Only the envelope is ever made `.required`. Required on the 30 km box,
    /// "Stowe, VT" typed in Boston would find nothing; required everywhere, the
    /// envelope's centre would rank every search from western Maine.
    static func searchBias(around region: MKCoordinateRegion) -> SearchBias {
        let envelope = MKCoordinateRegion.newEnglandEnvelope
        let tooWide = region.span.latitudeDelta > envelope.span.latitudeDelta
            || region.span.longitudeDelta > envelope.span.longitudeDelta
        if tooWide || !contains(region.center) {
            return SearchBias(region: envelope, restricted: true)
        }
        return SearchBias(region: region, restricted: false)
    }

    // MARK: - The outline

    private static let rings: [Ring] = NewEnglandBoundary.rings.map(Ring.init)

    /// One closed ring of the outline, with its bounding box.
    private struct Ring {
        /// Latitude, longitude pairs, flattened, as generated.
        let points: [Double]
        let south: Double, north: Double, west: Double, east: Double

        init(_ points: [Double]) {
            self.points = points
            let lats = stride(from: 0, to: points.count, by: 2).map { points[$0] }
            let lons = stride(from: 1, to: points.count, by: 2).map { points[$0] }
            south = lats.min() ?? 0; north = lats.max() ?? 0
            west = lons.min() ?? 0; east = lons.max() ?? 0
        }

        /// Even-odd crossing test, treating degrees as planar. The edges are
        /// a couple of hundred metres long, so the curve of the earth between
        /// two vertices is far inside the 10 m the vertices were rounded to.
        func contains(lat: Double, lon: Double) -> Bool {
            guard lat >= south, lat <= north, lon >= west, lon <= east else { return false }
            let count = points.count / 2
            var inside = false
            var j = count - 1
            for i in 0..<count {
                let latI = points[2 * i], lonI = points[2 * i + 1]
                let latJ = points[2 * j], lonJ = points[2 * j + 1]
                if (latI > lat) != (latJ > lat) {
                    let crossing = lonI + (lat - latI) / (latJ - latI) * (lonJ - lonI)
                    if lon < crossing { inside.toggle() }
                }
                j = i
            }
            return inside
        }
    }
}

/// Whether the phone is in New England, as of the last fix the app looked at.
///
/// Kept in one place, on the `LocationManager` both planning models share, and
/// written by every fix the app plans with: the check at launch and both
/// My Location paths. Home's Loop row reads it.
enum RegionStatus: Equatable {
    case unknown
    case inside
    case outside

    init(_ coordinate: CLLocationCoordinate2D) {
        self = NewEngland.contains(coordinate) ? .inside : .outside
    }
}

// MARK: - Applying the bias

extension MKLocalSearch.Request {
    /// Rank this search around `region`, kept to New England. See
    /// `NewEngland.searchBias`.
    func rank(around region: MKCoordinateRegion) {
        let bias = NewEngland.searchBias(around: region)
        self.region = bias.region
        if #available(iOS 18, *) { regionPriority = bias.restricted ? .required : .default }
    }
}

extension MKLocalSearchCompleter {
    /// Rank completions around `region`, kept to New England.
    ///
    /// **No `regionPriority`, deliberately**, though the typed search gets one.
    /// Measured on iOS 26.4, `.required` does not restrict the completer: with
    /// the region pinned to New England "Times Square" still offered Mumbai,
    /// and pinned to the 30 km box round Boston "Stowe" still offered Stowe, VT.
    /// In the one query of 24 where it changed anything, it moved Albany, NH
    /// from second to tenth, below Albany, Georgia and Oregon: after filtering,
    /// off the five rows the field shows. `allowsSuggestion` is what keeps
    /// other states out of the list.
    func rank(around region: MKCoordinateRegion) {
        self.region = NewEngland.searchBias(around: region).region
    }
}
